version: "3.8"
        
services:
    nginx:
        image: nginx:latest
        environment:
            TZ: "Asia/Istanbul"
        depends_on:
            - phpfpm 
        volumes:
            - "./conf/nginx-default.conf:/etc/nginx/conf.d/default.conf"
            - "./volumes/log/nginx:/var/log/nginx:rw"
            - "./dist:/public"
        ports:
            - "80:80"
    phpfpm:
        build:
            context: ./conf
            dockerfile: php-fpm-dockerfile
        environment: 
            COMPOSER: "/composer.json"
        volumes:
            - "./public/index.php:/public/index.php:consistent"
            - "./private:/private:consistent"
            - "./conf/session_redis.ini:/etc/php7/conf.d/session_redis.ini"
            - "./conf/composer.json:/composer.json"
        ports:
            - "9000:9000"
    redis:
        image: redis:latest
        environment:
            TZ: "Asia/Istanbul"
        volumes:
            - "./volumes/redis:/data:rw"
        expose: 
            - "6379"
        ports:
            - "6379:6379"
    mariadb:
        image: mariadb:latest
        environment:
            TZ: "Asia/Istanbul"
            MYSQL_ROOT_PASSWORD: "40801772"
        volumes:
            - "./src/sql/init/maria_master:/docker-entrypoint-initdb.d"
            - "./volumes/maria:/var/lib/mysql:rw"
        expose: 
            - "3306"
        ports:
            - "3306:3306"
    mongodb:
        image: mongo:latest
        environment:
            TZ: "Asia/Istanbul"
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
            - 27017:27017
        expose: 
            - "27017"
        volumes:
            - ./volumes/mongo:/data/db